{
    "name": "Codestra Middleware Bridge",
    "version": "19.0.2.5.1",
    "summary": "Authenticated, idempotent Odoo middleware service API",
    "author": "Codestra",
    "license": "LGPL-3",
    "depends": [
        "contacts",
        "crm",
        "mail",
        "utm",
        "call_center_core",
        "call_center_compliance",
        "codestra_cc_core",
        "codestra_cc_crm",
        "codestra_cc_helpdesk",
        "codestra_integration_hub",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/crm_stages.xml",
    ],
    "installable": True,
    "application": False,
}
